#!/bin/bash
[ ! -d ~/.nvm ] && curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

FILES=(gitconfig profile vimrc zshrc)
for f in "${FILES[@]}"
do
    if [ -f ~/.$f ]; then
        echo "~/.$f exists...remove to use .dotfile version";
    else
        rm -f ~/.$f
        ln -s "$DIR/$f" ~/.$f
    fi
done

if [ -f ~/.vim/colors/solarized.vim ]; then
    echo "~/.vim/colors/solarized.vim exists...remove to use .dotfile version"
    exit 1
fi

mkdir -p ~/.vim/colors
ln -s "$DIR/vim-colors-solarized/colors/solarized.vim" ~/.vim/colors/solarized.vim

if command -v dnf; then 
    sudo dnf install -y xclip xsel
fi