#!/bin/bash
# set -x
cd `dirname "$0"` # this script assumes we're in the source directory
git submodule update --init --recursive

NVM_DIR=~/.nvm
[ ! -d $NVM_DIR ] && curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
# Make sure nvm is up-to-date.
(
    cd "$NVM_DIR"
    git fetch --tags origin
    git checkout `git describe --abbrev=0 --tags --match "v[0-9]*" $(git rev-list --tags --max-count=1)`
) && \. "$NVM_DIR/nvm.sh"

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

FILES=(gitconfig profile vimrc zshrc)
for f in "${FILES[@]}"
do
    if [ -f ~/.$f ]; then
        echo "~/.$f exists...remove to use .dotfile version";
    else
        rm -f ~/.$f
        ln -s "$DIR/$f" ~/.$f
    fi
done

if [ -f ~/.vim/colors/solarized.vim ]; then
    echo "~/.vim/colors/solarized.vim exists...remove to use .dotfile version"
else
    mkdir -p ~/.vim/colors
    ln -s "$DIR/vim-colors-solarized/colors/solarized.vim" ~/.vim/colors/solarized.vim
fi

if command -v dnf &> /dev/null; then 
    sudo dnf install -y xclip xsel
    
    mkdir -p ~/.local/share/applications 
    ln -s "$DIR/uefi-reboot.desktop" ~/.local/share/applications/uefi-reboot.desktop
    ln -s "$DIR/goto-windows.desktop" ~/.local/share/applications/goto-windows.desktop
    sudo ln -s ~/.dotfiles/scripts/goto-windows /usr/local/bin/goto-windows
fi
