#!/bin/bash
# set -x
set -e

DIR=$(dirname -- "$(readlink -f -- "$0")")
source $DIR/helpers
if [ command -v docker &> /dev/null ]; then
    echo "Docker is already installed. Skipping installation."
    exit 0
fi

case $(get_distro_id) in
    fedora)
        # https://docs.docker.com/engine/install/fedora/
        # remove conflicting packages
        sudo dnf remove docker \
                    docker-client \
                    docker-client-latest \
                    docker-common \
                    docker-latest \
                    docker-latest-logrotate \
                    docker-logrotate \
                    docker-selinux \
                    docker-engine-selinux \
                    docker-engine;

        # set up the repository
        sudo dnf config-manager addrepo --from-repofile https://download.docker.com/linux/fedora/docker-ce.repo
        # install docker
        sudo dnf install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
        sudo systemctl enable --now docker
        ;;
    darwin)
        open https://desktop.docker.com/mac/main/arm64/Docker.dmg
        exit 0;
        ;;
    *)
        echo "Unknown or unsupported distribution."
        exit 1
        ;;
esac

