export ZSH=~/.dotfiles/oh-my-zsh
# ZSH_THEME="spaceship"
source ~/.dotfiles/configs/prompt

DISABLE_UPDATE_PROMPT=true

COMPLETION_WAITING_DOTS="true"

DISABLE_UNTRACKED_FILES_DIRTY="true"
ZSH_CUSTOM=~/.dotfiles/zsh/

plugins=(
  git
  fnm
)

source $ZSH/oh-my-zsh.sh

setopt hist_ignore_all_dups
setopt hist_expire_dups_first
setopt hist_save_no_dups
setopt hist_find_no_dups
setopt hist_no_store
setopt hist_no_functions
setopt hist_reduce_blanks


source ~/.dotfiles/configs/aliases
source ~/.dotfiles/configs/vars

bindkey -e

autoload zmv
autoload -Uz bracketed-paste-magic
zle -N bracketed-paste bracketed-paste-magic

