#!/usr/bin/env bash

if [ $# -eq 0 ] ; then
    echo "must specify repo name"
	exit 1
fi

target=$2
if [ $# -eq 1 ] ; then
	target="${1//./-}"
fi

git clone "git@github.com:NextThought/$1.git" $target
