#!/bin/bash
# See https://salferrarello.com/mac-pfctl-port-forwarding/

echo "
rdr pass inet proto tcp from any to any port 80 -> 127.0.0.1 port 8080
rdr pass inet proto tcp from any to any port 443 -> 127.0.0.1 port 8443
" | sudo pfctl -ef - 2> /dev/null