#!/bin/bash
MAILS=$WORKSPACE_DIR/buildout/var/maildir/new/*

runmail(){
	FILE=`basename $1`
	echo -n "Sending: $FILE..."

	if sendmail -t jonathan.grimes@nextthought.com < $1 ; then
		rm $1;
		echo "sent!";
	else
		echo "failed";
	fi
	echo ""
}



for f in $MAILS
do
	runmail $f
done

