#!/usr/bin/env bash


# echo "
# rdr pass inet proto tcp from any to any port 80 -> 127.0.0.1 port 8082
# rdr pass inet proto tcp from any to any port 443 -> 127.0.0.1 port 8443
# " | sudo pfctl -ef -

echo "
rdr pass inet proto tcp from any to any port 80 -> 127.0.0.1 port 8082
rdr pass inet proto tcp from any to any port 443 -> 127.0.0.1 port 8443
" | sudo pfctl -ef - >/dev/null 2>&1 
printf "Add Port Forwarding (80 => 8082)\nAdd Port Forwarding (443 => 8443)\n"

# Stop forwarding:
# sudo pfctl -F all -f /etc/pf.conf