#!/usr/bin/env bash

# See: https://austincloud.guru/2018/11/27/1password-cli-tricks/
eval 'SESSION=(${!'"OP_SESSION_"'@})'
if [[ -z $SESSION ]]; then
    echo "Login required: eval \$(op signin accountname)"
    exit 1;
fi

if ! command -v base64 &> /dev/null; then
    echo "base64 command missing."
    exit 1;
fi

if ! command -v op &> /dev/null; then
    URL=https://1password.com/downloads/command-line/
    echo "1password cli missing: $URL"
    exit 1;
fi

if ! command -v gpg &> /dev/null; then
    echo "Skipping gpg trust restore, gpg not found."
else
    op item get "gpg-backup" --fields label=private | base64 --decode | gpg --import --allow-secret-key-import --import-options restore
fi

# op item get "ssh" --format json | jq -r '.details.notesPlain'|ssh-add -

mkdir -p ~/.ssh

op item get "ssh-backup" --fields label=notesPlain > ~/.ssh/config
op item get "ssh-backup" --fields label=private | base64 --decode > ~/.ssh/id_rsa
op item get "ssh-backup" --fields label=public > ~/.ssh/id_rsa.pub

chmod 600 ~/.ssh/config
chmod 600 ~/.ssh/id_rsa
chmod 600 ~/.ssh/id_rsa.pub
ssh-add ~/.ssh/id_rsa
