#!/bin/bash
# set -x
set -e
COMMAND=''
if command -v brew &> /dev/null; then 
    COMMAND="brew"
elif command -v dnf &> /dev/null; then 
    COMMAND="sudo dnf"
elif command -v apt &> /dev/null; then
    COMMAND="sudo apt"
fi

if [ -z "$COMMAND" ]; then
    echo "No package manager found"
    exit 1
fi

$COMMAND install bat