#!/bin/bash
# set -x
set -e
{ #prevent exec until fully downloaded
    # Install pup
    if ! command -v pup &> /dev/null; then
        (
            cd ~/Downloads
            wget -q -c https://github.com/ericchiang/pup/releases/download/v0.4.0/pup_v0.4.0_linux_amd64.zip -O pup.zip
            unzip pup.zip pup; rm -f pup.zip
            sudo mv ~/Downloads/pup /usr/local/bin
        )
    fi
}