#!/bin/bash
# set -x
set -e
{

    if [[ "$OSTYPE" == "darwin"* ]]; then
        if [ ! -d "/Applications/1Password.app" ]; then
        (
            echo "Downloading 1Password..."
            cd ~/Downloads;
            curl -fsSL https://downloads.1password.com/mac/1Password.zip -o 1Password.zip &&
                unzip -x 1Password.zip &&
                rm 1Password.zip &&
                open "1Password Installer.app"
        )
        fi
    elif ! command -v 1password &> /dev/null; then           

        if command -v dnf &> /dev/null; then 

            #1password repo
            sudo rpm --import https://downloads.1password.com/linux/keys/1password.asc
            sudo sh -c 'echo -e "[1password]\nname=1Password Stable Channel\nbaseurl=https://downloads.1password.com/linux/rpm/stable/\$basearch\nenabled=1\ngpgcheck=1\nrepo_gpgcheck=1\ngpgkey=\"https://downloads.1password.com/linux/keys/1password.asc\"" > /etc/yum.repos.d/1password.repo'
            
            sudo dnf install 1password 1password-cli

        elif command -v apt-get &> /dev/null; then

            curl -sS https://downloads.1password.com/linux/keys/1password.asc | sudo gpg --dearmor --output /usr/share/keyrings/1password-archive-keyring.gpg
            echo 'deb [arch=amd64 signed-by=/usr/share/keyrings/1password-archive-keyring.gpg] https://downloads.1password.com/linux/debian/amd64 stable main' | sudo tee /etc/apt/sources.list.d/1password.list
            sudo mkdir -p /etc/debsig/policies/AC2D62742012EA22/
            curl -sS https://downloads.1password.com/linux/debian/debsig/1password.pol | sudo tee /etc/debsig/policies/AC2D62742012EA22/1password.pol
            sudo mkdir -p /usr/share/debsig/keyrings/AC2D62742012EA22
            curl -sS https://downloads.1password.com/linux/keys/1password.asc | sudo gpg --dearmor --output /usr/share/debsig/keyrings/AC2D62742012EA22/debsig.gpg
            
            sudo apt update && sudo apt install 1password 1password-cli

        else
            echo "cannot install 1password automatically... ";
        fi
    else
        echo '1password already installed'
    fi
}