#!/bin/bash
# set -x
set -e
CWD=`dirname -- "$( readlink -f -- "$0"; )"`
{
    sh $CWD/install-pup

    # AppImageLauncher service
    if ! command -v AppImageLauncher &> /dev/null; then
        
        API="https://api.github.com/repos/TheAssassin/AppImageLauncher/releases/latest"

        if command -v dnf &> /dev/null; then 
            PATH=$(curl -Ls -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" $API | jq -r '.assets[] | select(.name | contains("x86_64.rpm")) | .browser_download_url')
            sudo dnf install https://github.com$PATH;
            return;
        if

        if command -v apt &> /dev/null; then
            curl -Ls -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" $API | jq -r '.assets[] | select(.name | contains("x86_64.AppImage")) | .browser_download_url' | xargs curl -fsSL -o ~/Downloads/appimagelauncher-lite.AppImage
            return;
        fi

        echo "AppImageLauncher not installed, platform not handled"
    fi
}