#!/bin/bash
# set -x
set -e
{
    API="https://api.github.com/repos/so-fancy/diff-so-fancy/releases/latest"

    # diff-so-fancy 
    if ! command -v diff-so-fancy &> /dev/null; then
        mkdir -p ~/Downloads
        curl -sL -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" $API \
            | jq -r '.assets[] | select(.name | contains("diff-so-fancy")) | .browser_download_url' \
            | xargs curl -fsSL -o ~/Downloads/diff-so-fancy

        chmod +x ~/Downloads/diff-so-fancy
        mkdir -p ~/.local/bin
        mv ~/Downloads/diff-so-fancy ~/.local/bin/diff-so-fancy
    fi
}