#!/bin/bash
# set -x
set -e
{ #prevent exec until fully downloaded

function install() {

    if [[ "$OSTYPE" == "darwin"* ]]; then
        if [ ! -d "/Applications/Visual Studio Code.app" ]; then
        (
            echo "Downloading Visual Studio Code..."
            cd ~/Downloads
            curl -fsSL -o vscode.zip https://code.visualstudio.com/sha/download\?build\=stable\&os\=darwin-arm64 &&
                unzip vscode.zip &&
                rm vscode.zip
            sudo mv "./Visual Studio Code.app" "/Applications/Visual Studio Code.app"
        )
        fi
        return
    fi
    
    if command -v dnf &> /dev/null; then 

        sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc
        sudo sh -c 'echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/vscode.repo'

        dnf check-update
        sudo dnf install code

    elif command -v apt &> /dev/null; then

        sudo apt install wget gpg
        wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > packages.microsoft.gpg
        sudo install -D -o root -g root -m 644 packages.microsoft.gpg /etc/apt/keyrings/packages.microsoft.gpg
        sudo sh -c 'echo "deb [arch=amd64,arm64,armhf signed-by=/etc/apt/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main" > /etc/apt/sources.list.d/vscode.list'
        rm -f packages.microsoft.gpg
    
        sudo apt install apt-transport-https
        sudo apt update
        sudo apt install code 

    fi

    # xdg-mime default code.desktop text/plain
    # sudo update-alternatives --set editor /usr/bin/code
    # sudo update-alternatives --install /usr/bin/editor editor $(which code) 10

}

install 

}