#!/bin/bash

function install_my_tool() {
    for cmd in "$@"; do
        if ! command -v $cmd &>/dev/null; then
            (
                COMMAND=''
                if command -v brew &>/dev/null; then
                    COMMAND="brew"
                elif command -v dnf &>/dev/null; then
                    COMMAND="sudo dnf -y"
                elif command -v apt-get &>/dev/null; then
                    COMMAND="sudo apt-get -y"
                fi

                if [ -z "$COMMAND" ]; then
                    echo "No package manager found"
                    exit 1
                fi

                $COMMAND install $cmd
            )
        else
            echo "$cmd already installed"
        fi
    done
}
