#!/bin/bash
set -e

if [ "$1" == "--help" ] || [ "$1" == "-h" ]; then
    echo "Usage: $0 [--regenerate-lockfile|-r]"
    echo "  --regenerate-lockfile, -r  Regenerate the lock file by deleting it and reinstalling dependencies."
    exit 0
fi

LOCKFILE_TO_MANAGER=(
    "package-lock.json:npm"
    "yarn.lock:yarn"
    "pnpm-lock.yaml:pnpm"
    "bun.lockb:bun"
    "bun.lock:bun"
)
PCK_MGR=""
for entry in "${LOCKFILE_TO_MANAGER[@]}"; do
    FILE=${entry%%:*}
    MGR=${entry#*:}
    # echo "Checking for $FILE to determine package manager..."
    if [ -f "./$FILE" ]; then
        # echo "Found $FILE, using $MGR as the package manager."
        if command -v "$MGR" &> /dev/null; then      
            PCK_MGR=$MGR
            break
        else 
            echo "Warning: $FILE is not installed. Skipping ${MGR}."
        fi
    fi
done
REGENERATE_LOCKFILE= [ "$1" == "--regenerate-lockfile" ] || [ "$1" == "-r" ]

if [ -z "$PCK_MGR" ]; then
    echo "No supported package manager found. Please install npm, yarn, pnpm, or bun."
    exit 1
fi



if [ -d ./node_modules ]; then
    TEMP_DIR=$(mktemp -d /tmp/node_modules.XXXXXXXXX)
    mv ./node_modules $TEMP_DIR
    rm -rf $TEMP_DIR &
fi

if $REGENERATE_LOCKFILE; then
    echo "Regenerating lock file..."
    rm -f ./package-lock.json ./yarn.lock ./pnpm-lock.yaml ./bun.lockb ./bun.lock
fi

echo "Installing dependencies using $PCK_MGR..."
$PCK_MGR install
