#!/bin/bash
# find . -type d -name 'node_modules' \( -not -name 'Library' -not -path '*/\.*' -not -path '*/node_modules/*' \) -exec spotlight-ignore '{}' \;
find . -type d \( -name 'Library' -o -name '\.*' -not -name '\.' \) -prune \
    -o -type d \( \
        -name 'node_modules' \
    \) \
    -prune \
    -exec spotlight-ignore '{}' \;